### ISSUE TITLE
What is the right way to pass apllication context to Viewmodel?

### ISSUE THREAD

**Issue by glush** [burnoo/cokoin#1]
App fails with:

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
    E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
    E  Caused by: java.lang.reflect.InvocationTargetException
    E      at java.lang.reflect.Method.invoke(Native Method)
    E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    E      ... 1 more
    E  Caused by: org.koin.android.error.MissingAndroidContextException: Can't resolve Application instance. Please use androidContext() function in your KoinApplication configuration.
```
```kotlin                 
val myModule = module {
    viewModel { HelmMadeViewModel(androidApplication()) }
}                
```                         
Even I use: 
```kotlin
startKoin {
    androidLogger()
    androidContext(this@MyApplication)
    modules(helmMadeModule)
}
```

**Comment by burnoo** [comment]
You can add `androidContext` in `@Composable Koin` configuration block:
```kotlin
@Composable
fun App() {
    val context = LocalContext.current
    Koin(appDeclaration = { 
        androidContext(context)
        modules(appModule) 
    }) {
        Screen()
    }
}
```
Then You can use `androidContext()` or `get()` in modules:
```kotlin
val appModule = module {
    viewModel { MainViewModel(context = androidContext()) }
}
```

**Comment by glush** [comment]
Thnx. It works like a charm.
